apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helsearbeidsgiver-bigquery
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
    app: helsearbeidsgiver-bigquery
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
    timeout: 2
  readiness:
    path: isready
    initialDelay: 10
    timeout: 2
  prometheus:
    enabled: true
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  envFrom:
  env:
    - name: KOIN_PROFILE
      value: PREPROD
    - name: GCP_PRJ_ID
      value: helsearbeidsgiver-dev-6d06
    - name: KAFKA_RAPID_TOPIC
      value: helsearbeidsgiver.spinn-bq
    - name: KAFKA_CONSUMER_GROUP_ID
      value: helsearbeidsgiver-bigquery-v1
  gcp:
    bigQueryDatasets:
      - name: im_bigquery_v1_dataset_dev
        permission: READWRITE
  kafka:
    pool: nav-dev
